version: "3"
services:
    mongo:
        image: mongo
        container_name: "mongo-container"
        environment:
            - MONGO_INITDB_DATABASE=Users
            - MONGO_INITDB_ROOT_USERNAME=sammy
            - MONGO_INITDB_ROOT_PASSWORD=123456
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    redis:
      image: redis:alpine
      hostname: redis
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --save 20 1 --loglevel warning --requirepass cookies
      volumes:
        - redis-data:/data
    redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_PASSWORD=cookies
      restart: always
      ports:
        - "6380:8081"
        - redis
volumes:
  redis-data:
