export default {
    title: 'Next.js Blogue With Tailwind CSS and Contentlayer',
    author: 'SammyShehter',
    headerTitle: 'Next.js Blog',
    description: 'A blog created with Next.js, Tailwind.css and contentlayer.',
    language: 'en-us',
    theme: 'system',
    siteUrl: 'https://blogue.sammyshehter.com',
    siteLogo: '/logo.png',
    socialBanner: '/social-banner.png',
    email: 'sammyshehter@gmail.com', 
    github: 'https://github.com/sammyshehter',
    linkedin: 'https://www.linkedin.com/in/sammy-shehter',
    locale: 'en-US',
}